### ISSUE TITLE
Repository abandonned? 

### ISSUE THREAD

**Issue by mattduerrmeier** [smithmcgriff/Fedora-on-pinebookpro#9]
Good day,
I have made a significant upgrade to the README to make the installation instructions simpler to read and understand. 

I would like to help with this repository. If you don't have the time to maintain it, I will gladly do so.

**Comment by bengtfredh** [comment]
@mattiasduerrmeier 
It is not what you asked, but I have copy/paste together an install script. I need help to test and improve:
https://github.com/bengtfredh/pinebook-pro-fedora-installer.git
